FROM python:3.8.6-alpine
ENV app /crawler-api
RUN mkdir $app
WORKDIR $app
COPY . $app
RUN apk add --update --no-cache libxml2-dev libxslt-dev g++ gcc libxslt-dev libffi libffi-dev openssl-dev
RUN pip3 install --no-cache-dir -r requirements.txt
